export const siteConfig = {
  siteName: 'Riad Tadarte',
  tagline: 'Guest house at the gates of the Sahara.',
  location: 'Hassi Labied, Merzouga, 52202',
  address: 'Hassilabiad Poste Merzouga Province Errachidia Maroc · Hassi Labied Merzouga, 52202',
  phone: '+212 668 563 565',
  email: 'riadtadarte@gmail.com',
  whatsappNumber: '212668563565',
  facebookUrl: 'https://facebook.com/tadartesahara.merzouga',
  instagramUrl: 'https://instagram.com/riad_tadarte',
  tripadvisorUrl: 'https://www.tripadvisor.com/Hotel_Review-g304017-d1911935-Reviews-Riad_Tadarte-Merzouga_Draa_Tafilalet.html',
  tripadvisorRating: '4.9',
  bookingUrl: 'https://www.booking.com/Share-n1pPPau',
  bookingRating: '9.8',
  googleMapsUrl: 'https://maps.app.goo.gl/r6yb8PeVxcQk2m2RA',
  googleMapsRating: '4.9',
} as const

export const galleryImages = [
  { src: '/images/gallery/photo_001.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_001' },
  { src: '/images/gallery/photo_002.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_002' },
  { src: '/images/gallery/photo_003.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_003' },
  { src: '/images/gallery/photo_004.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_004' },
  { src: '/images/gallery/photo_005.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_005' },
  { src: '/images/gallery/photo_006.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_006' },
  { src: '/images/gallery/photo_007.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_007' },
  { src: '/images/gallery/photo_008.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_008' },
  { src: '/images/gallery/photo_009.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_009' },
  { src: '/images/gallery/photo_010.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_010' },
  { src: '/images/gallery/photo_011.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_011' },
  { src: '/images/gallery/photo_012.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_012' },
  { src: '/images/gallery/photo_013.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_013' },
  { src: '/images/gallery/photo_014.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_014' },
  { src: '/images/gallery/photo_015.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_015' },
  { src: '/images/gallery/photo_016.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_016' },
  { src: '/images/gallery/photo_017.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_017' },
  { src: '/images/gallery/photo_018.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_018' },
  { src: '/images/gallery/photo_019.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_019' },
  { src: '/images/gallery/photo_020.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_020' },
  { src: '/images/gallery/photo_021.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_021' },
  { src: '/images/gallery/photo_022.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_022' },
  { src: '/images/gallery/photo_023.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_023' },
  { src: '/images/gallery/photo_024.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_024' },
  { src: '/images/gallery/photo_025.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_025' },
  { src: '/images/gallery/photo_026.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_026' },
  { src: '/images/gallery/photo_027.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_027' },
  { src: '/images/gallery/photo_028.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_028' },
  { src: '/images/gallery/photo_029.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_029' },
  { src: '/images/gallery/photo_030.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_030' },
  { src: '/images/gallery/photo_031.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_031' },
  { src: '/images/gallery/photo_032.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_032' },
  { src: '/images/gallery/photo_033.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_033' },
  { src: '/images/gallery/photo_034.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_034' },
  { src: '/images/gallery/photo_035.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_035' },
  { src: '/images/gallery/photo_036.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_036' },
  { src: '/images/gallery/photo_037.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_037' },
  { src: '/images/gallery/photo_038.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_038' },
  { src: '/images/gallery/photo_039.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_039' },
  { src: '/images/gallery/photo_040.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_040' },
  { src: '/images/gallery/photo_041.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_041' },
  { src: '/images/gallery/photo_042.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_042' },
  { src: '/images/gallery/photo_043.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_043' },
  { src: '/images/gallery/photo_044.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_044' },
  { src: '/images/gallery/photo_045.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_045' },
  { src: '/images/gallery/photo_046.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_046' },
  { src: '/images/gallery/photo_047.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_047' },
  { src: '/images/gallery/photo_048.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_048' },
  { src: '/images/gallery/photo_049.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_049' },
  { src: '/images/gallery/photo_050.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_050' },
  { src: '/images/gallery/photo_051.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_051' },
  { src: '/images/gallery/photo_052.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_052' },
  { src: '/images/gallery/photo_053.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_053' },
  { src: '/images/gallery/photo_054.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_054' },
  { src: '/images/gallery/photo_055.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_055' },
  { src: '/images/gallery/photo_056.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_056' },
  { src: '/images/gallery/photo_057.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_057' },
  { src: '/images/gallery/photo_058.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_058' },
  { src: '/images/gallery/photo_059.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_059' },
  { src: '/images/gallery/photo_060.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_060' },
  { src: '/images/gallery/photo_061.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_061' },
  { src: '/images/gallery/photo_062.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_062' },
  { src: '/images/gallery/photo_063.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_063' },
  { src: '/images/gallery/photo_064.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_064' },
  { src: '/images/gallery/photo_065.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_065' },
  { src: '/images/gallery/photo_066.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_066' },
  { src: '/images/gallery/photo_067.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_067' },
  { src: '/images/gallery/photo_068.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_068' },
  { src: '/images/gallery/photo_069.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_069' },
  { src: '/images/gallery/photo_070.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_070' },
  { src: '/images/gallery/photo_071.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_071' },
  { src: '/images/gallery/photo_072.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_072' },
  { src: '/images/gallery/photo_073.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_073' },
  { src: '/images/gallery/photo_074.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_074' },
  { src: '/images/gallery/photo_075.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_075' },
  { src: '/images/gallery/photo_076.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_076' },
  { src: '/images/gallery/photo_077.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_077' },
  { src: '/images/gallery/photo_078.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_078' },
  { src: '/images/gallery/photo_079.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_079' },
  { src: '/images/gallery/photo_080.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_080' },
  { src: '/images/gallery/photo_081.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_081' },
  { src: '/images/gallery/photo_082.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_082' },
  { src: '/images/gallery/photo_083.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_083' },
  { src: '/images/gallery/photo_084.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_084' },
  { src: '/images/gallery/photo_085.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_085' },
  { src: '/images/gallery/photo_086.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_086' },
  { src: '/images/gallery/photo_087.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_087' },
  { src: '/images/gallery/photo_088.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_088' },
  { src: '/images/gallery/photo_089.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_089' },
  { src: '/images/gallery/photo_090.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_090' },
  { src: '/images/gallery/photo_091.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_091' },
  { src: '/images/gallery/photo_092.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_092' },
  { src: '/images/gallery/photo_093.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_093' },
  { src: '/images/gallery/photo_094.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_094' },
  { src: '/images/gallery/photo_095.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_095' },
  { src: '/images/gallery/photo_096.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_096' },
  { src: '/images/gallery/photo_097.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_097' },
  { src: '/images/gallery/photo_098.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_098' },
  { src: '/images/gallery/photo_099.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_099' },
  { src: '/images/gallery/photo_100.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_100' },
  { src: '/images/gallery/photo_101.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_101' },
  { src: '/images/gallery/photo_102.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_102' },
  { src: '/images/gallery/photo_103.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_103' },
  { src: '/images/gallery/photo_104.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_104' },
  { src: '/images/gallery/photo_105.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_105' },
  { src: '/images/gallery/photo_106.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_106' },
  { src: '/images/gallery/photo_107.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_107' },
  { src: '/images/gallery/photo_108.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_108' },
  { src: '/images/gallery/photo_109.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_109' },
  { src: '/images/gallery/photo_110.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_110' },
  { src: '/images/gallery/photo_111.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_111' },
  { src: '/images/gallery/photo_112.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_112' },
  { src: '/images/gallery/photo_113.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_113' },
  { src: '/images/gallery/photo_114.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_114' },
  { src: '/images/gallery/photo_115.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_115' },
  { src: '/images/gallery/photo_116.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_116' },
  { src: '/images/gallery/photo_117.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_117' },
  { src: '/images/gallery/photo_118.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_118' },
  { src: '/images/gallery/photo_119.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_119' },
  { src: '/images/gallery/photo_120.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_120' },
  { src: '/images/gallery/photo_121.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_121' },
  { src: '/images/gallery/photo_122.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_122' },
  { src: '/images/gallery/photo_123.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_123' },
  { src: '/images/gallery/photo_124.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_124' },
  { src: '/images/gallery/photo_125.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_125' },
  { src: '/images/gallery/photo_126.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_126' },
  { src: '/images/gallery/photo_127.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_127' },
  { src: '/images/gallery/photo_128.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_128' },
  { src: '/images/gallery/photo_129.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_129' },
  { src: '/images/gallery/photo_130.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_130' },
  { src: '/images/gallery/photo_131.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_131' },
  { src: '/images/gallery/photo_132.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_132' },
  { src: '/images/gallery/photo_133.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_133' },
  { src: '/images/gallery/photo_134.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_134' },
  { src: '/images/gallery/photo_135.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_135' },
  { src: '/images/gallery/photo_136.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_136' },
  { src: '/images/gallery/photo_137.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_137' },
  { src: '/images/gallery/photo_138.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_138' },
  { src: '/images/gallery/photo_139.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_139' },
  { src: '/images/gallery/photo_140.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_140' },
  { src: '/images/gallery/photo_141.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_141' },
  { src: '/images/gallery/photo_142.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_142' },
  { src: '/images/gallery/photo_143.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_143' },
  { src: '/images/gallery/photo_144.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_144' },
  { src: '/images/gallery/photo_145.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_145' },
  { src: '/images/gallery/photo_146.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_146' },
  { src: '/images/gallery/photo_147.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_147' },
  { src: '/images/gallery/photo_148.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_148' },
  { src: '/images/gallery/photo_149.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_149' },
  { src: '/images/gallery/photo_150.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_150' },
  { src: '/images/gallery/photo_151.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_151' },
  { src: '/images/gallery/photo_152.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_152' },
  { src: '/images/gallery/photo_153.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_153' },
  { src: '/images/gallery/photo_154.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_154' },
  { src: '/images/gallery/photo_155.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_155' },
  { src: '/images/gallery/photo_156.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_156' },
  { src: '/images/gallery/photo_157.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_157' },
  { src: '/images/gallery/photo_158.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_158' },
  { src: '/images/gallery/photo_159.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_159' },
  { src: '/images/gallery/photo_160.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_160' },
  { src: '/images/gallery/photo_161.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_161' },
  { src: '/images/gallery/photo_162.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_162' },
  { src: '/images/gallery/photo_163.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_163' },
  { src: '/images/gallery/photo_164.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_164' },
  { src: '/images/gallery/photo_165.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_165' },
  { src: '/images/gallery/photo_166.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_166' },
  { src: '/images/gallery/photo_167.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_167' },
  { src: '/images/gallery/photo_168.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_168' },
  { src: '/images/gallery/photo_169.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_169' },
  { src: '/images/gallery/photo_170.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_170' },
  { src: '/images/gallery/photo_171.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_171' },
  { src: '/images/gallery/photo_172.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_172' },
  { src: '/images/gallery/photo_173.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_173' },
  { src: '/images/gallery/photo_174.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_174' },
  { src: '/images/gallery/photo_175.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_175' },
  { src: '/images/gallery/photo_176.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_176' },
  { src: '/images/gallery/photo_177.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_177' },
  { src: '/images/gallery/photo_178.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_178' },
  { src: '/images/gallery/photo_179.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_179' },
  { src: '/images/gallery/photo_180.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_180' },
  { src: '/images/gallery/photo_181.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_181' },
  { src: '/images/gallery/photo_182.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_182' },
  { src: '/images/gallery/photo_183.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_183' },
  { src: '/images/gallery/photo_184.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_184' },
  { src: '/images/gallery/photo_185.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_185' },
  { src: '/images/gallery/photo_186.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_186' },
  { src: '/images/gallery/photo_187.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_187' },
  { src: '/images/gallery/photo_188.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_188' },
  { src: '/images/gallery/photo_189.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_189' },
  { src: '/images/gallery/photo_190.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_190' },
  { src: '/images/gallery/photo_191.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_191' },
  { src: '/images/gallery/photo_192.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_192' },
  { src: '/images/gallery/photo_193.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_193' },
  { src: '/images/gallery/photo_194.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_194' },
  { src: '/images/gallery/photo_195.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_195' },
  { src: '/images/gallery/photo_196.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_196' },
  { src: '/images/gallery/photo_197.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_197' },
  { src: '/images/gallery/photo_198.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_198' },
  { src: '/images/gallery/photo_199.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_199' },
  { src: '/images/gallery/photo_200.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_200' },
  { src: '/images/gallery/photo_201.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_201' },
  { src: '/images/gallery/photo_202.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_202' },
  { src: '/images/gallery/photo_203.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_203' },
  { src: '/images/gallery/photo_204.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_204' },
  { src: '/images/gallery/photo_205.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_205' },
  { src: '/images/gallery/photo_206.jpg', category: 'Gallery', alt: 'Riad Tadarte — photo_206' },
]

export const rooms = [
  { name: 'Chambre Double', description: 'Une chambre chaleureuse pour un séjour à deux.', capacity: '2 voyageurs', bed: '1 grand lit double', amenities: ['Climatisation', 'Salle de bains privée'], image: '/images/gallery/photo_197.jpg' },
  { name: 'Chambre Double ou Lits Jumeaux', description: 'Une chambre modulable avec deux configurations de couchage.', capacity: '2 voyageurs', bed: '1 lit simple et 1 lit double', amenities: ['Climatisation', 'Salle de bains privée'], image: '/images/gallery/photo_189.jpg' },
  { name: 'Chambre Triple', description: 'Un espace confortable pour les petites familles ou les amis.', capacity: '3 voyageurs', bed: '1 lit simple et 1 lit double', amenities: ['Climatisation', 'Salle de bains privée'], image: '/images/gallery/photo_200.jpg' },
  { name: 'Chambre Quadruple', description: 'Une chambre spacieuse pensée pour les groupes.', capacity: '4 voyageurs', bed: '4 lits simples', amenities: ['Climatisation', 'Salle de bains privée'], image: '/images/gallery/photo_199.jpg' },
  { name: 'Chambre Familiale avec Salle de Bains', description: 'Le confort d’un espace familial avec salle de bains privée.', capacity: '4 voyageurs', bed: '2 lits simples et 1 lit double', amenities: ['Climatisation', 'Salle de bains privée'], image: '/images/gallery/photo_195.jpg' },
]

export const experiences = [
  { number: '01', title: 'Tours en 4×4 dans la région', description: 'Explorez les villages, les oasis et les paysages remarquables de la région de Merzouga en véhicule tout-terrain.', image: '/images/4x4.jpg', bookable: true },
  { number: '02', title: 'Excursions en quad', description: 'Partez à l’aventure sur les pistes de sable et les dunes autour de Merzouga.', image: '/images/quad.jpg', bookable: true },
  { number: '03', title: 'Randonnée avec les dromadaires', description: 'Découvrez le désert au rythme paisible des dromadaires, avec un coucher de soleil inoubliable.', image: '/images/camel-tour.jpg', bookable: true },
  { number: '04', title: 'Nuit dans le désert', description: 'Passez une nuit authentique dans le désert, à la belle étoile, au cœur des dunes.', image: '/images/sahara-night.jpg', bookable: true },
  { number: '05', title: 'Trekking dans le désert', description: 'Partez pour plusieurs jours de marche et vivez une immersion profonde dans les paysages du Sahara.', image: '/images/multi-day-desert.jpg', bookable: true },
]
